// The transform scripts generated by tforge-gpu-tile and tforge-gpu-map.
// RUN: tensorforge-opt %s --tforge-gpu-pipeline="block-tile=32,64 thread-tile=2,4 print-script=1" -o /dev/null 2>&1 | FileCheck %s

// Block level: tile the root (the epilogue), fuse matmul then fill.
// CHECK: transform.structured.match attributes{tforge.root}
// CHECK: transform.structured.tile_using_forall %root tile_sizes [32, 64] (mapping = [#gpu.block<y>, #gpu.block<x>])
// CHECK: transform.structured.match ops{["linalg.matmul"]}
// CHECK: transform.structured.fuse_into_containing_op %p0 into %blk0
// CHECK: transform.structured.match ops{["linalg.fill"]}
// CHECK: transform.structured.fuse_into_containing_op %p1 into %blk1
// Thread level: 32/2 x 64/4 = 16 x 16 threads.
// CHECK: transform.structured.tile_using_forall %t0 num_threads [16, 16] (mapping = [#gpu.thread<y>, #gpu.thread<x>])
// CHECK: transform.structured.fuse_into_containing_op %pb0 into %thr0
// CHECK: transform.structured.fuse_into_containing_op %pb1 into %thr1
// Mapping: x threads along N.
// CHECK: transform.gpu.map_forall_to_blocks %arg0 generate_gpu_launch
// CHECK: transform.gpu.map_nested_forall_to_threads %l block_dims = [16, 16, 1]

func.func @entry(%x: tensor<128x64xf32>, %w: tensor<64x256xf32>, %b: tensor<256xf32>) -> tensor<128x256xf32> {
  %mm = tforge.matmul %x, %w : tensor<128x64xf32>, tensor<64x256xf32> -> tensor<128x256xf32>
  %ba = tforge.bias_add %mm, %b : tensor<128x256xf32>, tensor<256xf32> -> tensor<128x256xf32>
  %r = tforge.relu %ba : tensor<128x256xf32> -> tensor<128x256xf32>
  return %r : tensor<128x256xf32>
}
